# -*- coding: utf-8 -*-
"""RM92544_EX01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fWMG2SU9Npwt7jH8hmRUgT2gTQS9MJG8
"""

#Exercicio 1
#Instanciando variáveis
peso = float(input('Adicione seu peso em Kg: ')) 
altura = float(input('Adicione sua altura em metros: ')) 
#Calculando IMC
IMC = peso/(altura**2)
print("Seu IMC é: ", IMC)

#Definição de categoria baseada no IMC
if (IMC < 16):
  print("Baixo peso Grau III")
elif (IMC >= 16 and IMC <= 16.99):
  print("Baixo peso Grau II")
elif (IMC >= 17 and IMC <= 18.49):
  print("Baixo peso Grau I")
elif (IMC >= 18.50 and IMC <= 24.99):
  print("Peso ideal")
elif (IMC >= 25 and IMC <= 29.99):
  print("Sobrepeso")
elif (IMC >= 30 and IMC <= 34.99):
  print("Obesidade Grau I")
elif (IMC >= 35 and IMC <= 39.99):
  print("Obesidade Grau II")
elif (IMC >= 40 ):
  print("Obesidade Grau III")
else:
  print("Error")