# -*- coding: utf-8 -*-
"""RM92544_EX03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UxUc5eqImZ2YvJEyXXiIk1XvCZVwziUx
"""

#Exercicio 3
#Instanciando dias da semana
seg = int(input("Votos da Segunda: "))
ter = int(input("Votos da Terça: "))
qua = int(input("Votos da Quarta: "))
quin = int(input("Votos da Quinta: "))
sex = int(input("Votos da Sexta: "))


soma = [seg, ter, qua, quin, sex] 
voto = soma.index(max(soma))

 
if (voto == 0):
  print('''O dia escolhido foi Segunda-feira. \n 
  Votos\n
  Segunda | {}\n
  Terça   | {}\n
  Quarta  | {}\n
  Quinta  | {}\n
  Sexta   | {}\n'''.format(soma[0],soma[1],soma[2],soma[3],soma[4]))
elif (voto == 1):
  print('''O dia escolhido foi Terça-feira. \n 
  Votos\n
  Segunda | {}\n
  Terça   | {}\n
  Quarta  | {}\n
  Quinta  | {}\n
  Sexta   | {}\n'''.format(soma[0],soma[1],soma[2],soma[3],soma[4]))
elif (voto == 2):
  print('''O dia escolhido foi Quarta-feira. \n 
  Votos\n
  Segunda | {}\n
  Terça   | {}\n
  Quarta  | {}\n
  Quinta  | {}\n
  Sexta   | {}\n'''.format(soma[0],soma[1],soma[2],soma[3],soma[4]))
elif (voto == 3):
  print('''O dia escolhido foi Quinta-feira. \n 
  Votos\n
  Segunda | {}\n
  Terça   | {}\n
  Quarta  | {}\n
  Quinta  | {}\n
  Sexta   | {}\n'''.format(soma[0],soma[1],soma[2],soma[3],soma[4]))
elif (voto == 4):
  print('''O dia escolhido foi Sexta-feira. \n 
  Votos\n
  Segunda | {}\n
  Terça   | {}\n
  Quarta  | {}\n
  Quinta  | {}\n
  Sexta   | {}\n'''.format(soma[0],soma[1],soma[2],soma[3],soma[4]))
else: 
 print("Error")