# -*- coding: utf-8 -*-
"""RM92544_EX02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1etQ12xP54V5qQevpgFSzkivtDyofy_qz
"""

#Exercicio 2
#Instanciando variáveis
ass = float(input('''Adicione o numero do tipo de assinatura que você deseja calcular o Bonûs: \n
1 | Basic\n
2 | Silver\n
3 | Gold\n
4 | Platinum\n
'''))

#Recebendo faturamento
fat = float(input('Adicione seu faturamento anual: ')) 

#Calculando o bonus da assinatura
if (ass == 1):
  bonus = fat*0.3
  print("O bonûs de 30% do faturamento para a assinatura basic é de: ", bonus)
elif (ass == 2):
  bonus = fat*0.2
  print("O bonûs de 20% do faturamento para a assinatura silver é de: ", bonus)
elif (ass == 3):
  bonus = fat*0.1
  print("O bonûs de 10% do faturamento para a assinatura gold é de: ", bonus)
elif (ass == 4):
  bonus = fat*0.05
  print("O bonûs de 5% do faturamento para a assinatura platinum é de: ", bonus)
else: 
 print("O valor não está no indice")